### ISSUE TITLE
Single scenario / deterministic problem leads to "ArgumentError: reducing over an empty collection is not allowed"

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#12]
This error occurs at the line:
```julia
xmax = max(maximum(abs.(value.(values(ph_data.xhat)))), 1e-12)
```
Maybe there could be a check on the scenario tree to make sure it's not just a single branch / scenario?

**Comment by jmaack24** [comment]
My personal preference in this sort of situation is to issue a warning since it is an unusual thing for the user to ask for but is a valid thing to do.
