### ISSUE TITLE
Check on scenario tree probabilities is too tight

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#16]
Checking that the sum is exactly 1.0 leads to issues:
```julia
Total probability of scenarios in given scenario tree is 1.0000000000000002
```
I'm not able to get the sum of my probabilities any closer to 1 than that, and it strikes me also as close enough :P

**Comment by junglegobs** [comment]
Suggest changing the offending line to:
```julia
abs(psum - 1.0) > 1e-8 # or replace 1e-8 to a multiple of eps()
```

**Comment by jmaack24** [comment]
Oops. Should have thought of that when I was writing it.
