### ISSUE TITLE
Add debug statements to identify bottlenecks / issues

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#19]
I'm currently using this package to solve a large scale generation expansion planning model - 35 years / scenarios of demand and weather data (8760 hours each) with binaries of each hour to indicate load shedding events. For some values of a dual I use to force a reliability target, the algorithm gets stuch at "Initializing subproblems...", after which my workers eventually terminate (perhaps because some of the subproblems are idle for too long?) and then the algorithm errors.

I'm not sure exactly what is happening, but it would be nice to have debug statements to get some more information of the stages of the algorithm, e.g., `@debug "Solving subproblem..."`, `@debug "Subproblem ... solved."` 
`

**Comment by jmaack24** [comment]
A few questions:

1.  What is the error you are getting?
2. What are you running this problem on?
3. Have you tried running a smaller version of the problem? Does that work?

**Comment by jmaack24** [comment]
> it would be nice to have debug statements to get some more information of the stages of the algorithm, e.g., @debug "Solving subproblem...", @debug "Subproblem ... solved."

I am open to this but PH is designed to run with a large number of processes on HPC platforms using Julia's Distributed package (I've done 256 processes spread across 8 compute nodes) so some care must be taken with how it is implemented.

In my experiences using PH, most of the issues when it appears to "hang" are related to the subproblem model I'm giving it (either creating the subproblem or solving it).  In this case, debugging messages from PH are of limited help. That's the other reason I haven't worked on putting in more printing/logging statements.

**Comment by junglegobs** [comment]
I think I've figured out the problem - my sub-problems just take too long to solve, so eventually my cluster job just times out.

To be clear, the `@debug` statements only appear if `ENV["JULIA_DEBUG"] = "ProgressiveHedging"`. A similar solution would be to specify an additional log level. I understand that you may not want to do this though, given that anyway I managed to figure out what the problem was.

**Comment by junglegobs** [comment]
With the user implemented callbacks you could add debug statements anyway (although I agree that the utility of these is limited), so I'm closing this issue myself.
