### ISSUE TITLE
Add canned callbacks to example and explain them

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#22]
I assume you're probably aware this is an issue, but regarding the callbacks I wanted to note:

- The canned callbacks exist, but a new user wouldn't know about them from looking at the `Example.ipynb`
- I personally understand what the `variable_fixing` callback does, but a new user probably wouldn't and I don't know what `mean_deviation` does.
- `variable_fixing` isn't exported - I assume you would want to?

I assume you will write some more complete documentation eventually (I would also be happy to help there), but thought it would be useful creating an issue for this (at least for a new user to be aware of this).

**Comment by jmaack24** [comment]
Looks like I forgot to add the docstrings to those functions like I meant to.  I also forgot to add them as potential examples of implementing a callback in the `Callback` docstring. They are both implementations of things found in [(Watson & Woodruff 2010)](https://link.springer.com/article/10.1007/s10287-010-0125-4).

**Comment by junglegobs** [comment]
I missed the `mean_deviation` function, is that Section 2.3, "Termination criteria"? I didn't quite understand the nuance between that and the "lag parameter" (`fixing_variables`) heuristic.

**Comment by jmaack24** [comment]
The `mean_deviation` stuff is found in the first paragraph of section 2.3, yes.  In naming the function, I was trying to balance name length with description.  Not sure if it worked or not.  The full name in the paper is "normalized average per-scenario deviation from the 'average' solution".  It is basically just a mean relative absolute (as in absolute value) deviation from the conditional expectation value.  Another way to think about it is a relative L1 norm version of the variance.
