### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by jmaack24** [NREL/ProgressiveHedging.jl#33]
Add documentation to the PH repo.

**Comment by junglegobs** [comment]
Personal thoughts on documentation. 

Home:
- Outline features
- How to install

In a "User Guide" menu: 
- Getting started / Quick start - this would essentially just be the example that you're currently using
- Some words about parallelism with PH.jl (for users who are new to distributed computing)
- Use with integers - outline features / words of caution for when using PH.jl with integers
- Performance tips - just general tips on how to use PH.jl, e.g. reference to the callbacks

Seperately:
- Examples folder with examples (who would have thought?) of commonly used tasks, e.g. the callbacks that you implemented + developping your own, subproblem callbacks for iteratively tightening optimizer tolerances, and anything else deem useful.
  - I personally

And API.

Probably worth fleshing out the above more if you're ok with the above. 

I really like [COSMO.jl's](https://oxfordcontrol.github.io/COSMO.jl/stable/) documentation, so the above is mostly based off of that.

**Comment by junglegobs** [comment]
JFYI had a quick look through the docs and you may be interested to know that you can use ```@doctest - this will run the Julia code you put in it and tell you if it works or not (the documentation is built regardless as far as I know).

**Comment by junglegobs** [comment]
In other thoughts, I have no issue / like the current setup with just examples. I think a Performance Tips section would nonetheless be useful, as would Extending PH (though that's probably much less critical).

**Comment by jmaack24** [comment]
> JFYI had a quick look through the docs and you may be interested to know that you can use ```@doctest - this will run the Julia code you put in it and tell you if it works or not (the documentation is built regardless as far as I know).

I'm using the `@example` which runs the code and captures the output. That's how all the output values are obtained in the documentation.  The `jldoctest` tests for specific values from the example and I didn't want to go and figure out what the values should be (that's why I have all the stuff in the test directory).

**Comment by junglegobs** [comment]
Ignore me then, I said nothing :-)
