### ISSUE TITLE
ERROR: Penalty parameter must match across scenarios

### ISSUE THREAD

**Issue by junglegobs** [NREL/ProgressiveHedging.jl#35]
I get this error from time to time when I run my simulations. This only happens when I use the `ProportionalPenaltyParameter` or the `SEPPenaltyParameter`. I was wondering whether I was doing something weird with callbacks at some point (I use these to progressively tighten my problem), but this doesn't appear to be the case.

Any idea why this could happen? I will try to come up with a simple example where this is the case, but this is non-trivial because of the way my code is set up.

**Comment by jmaack24** [comment]
Those methods of setting the penalty parameter use the coefficients in the objective function to determine a penalty parameter value.  Both methods really only make sense if the coefficients in the objective functions are the same in every scenario.  If they are not, then you should use the scalar penalty parameter.

**Comment by jmaack24** [comment]
Both the `ProportionalPenaltyParameter` and the `SEPPenaltyParameter` should document this fact and warn users about it.  Maybe make the error message a bit clearer.

**Comment by junglegobs** [comment]
Hmmm, I think I really should have the same objective in each of my scenarios, but thank you for the tip.

**Comment by jmaack24** [comment]
> Hmmm, I think I really should have the same objective in each of my scenarios, but thank you for the tip.

The other possibility is that PH is identifying something as a consensus variable that is not for some reason.

**Comment by junglegobs** [comment]
I would like to re-open this, as I think it might not be a problem on my side. It seems that PH is confusing my first stage variables somehow, since it is mixing up the capacity costs of my generators. 

The following piece of code generates subproblems and checks that my offshore wind generator (which causes the error) always has the same capacity costs in the objective:
```julia
for i in 0:364
    id = PH.ScenarioID(i)
    js = build_GEP_scenario(id, param, configFile, sim, geppr_ts_file)
    gn = ("Offshore Wind", "1")
    cap_cost_wind_expr = js.model.ext[:expressions][:generatorCapacityCosts][gn,1]
    cap_cost_wind = last(values(first(cap_cost_wind_expr.terms)))
    if isapprox(cap_cost_wind, 158.7546010894153, rtol=1e-3) == false
        @show id
        @show cap_cost_wind
    end
end
```

So the issue is not that my objective differs between scenarios. It also seems to rather randomly confuse the first stage variable costs, since as I was editing the code to try and debug this and then it started confusing my onshore and offshore wind costs (previously it confused my offshore and CCGT capacity costs).

**Comment by junglegobs** [comment]
I think I know what's going on - the penalty parameter is a pointer, and when after my initial PH run this penalty parameter is not "reset". So for example I'll run an initial simulation with `PH.ProportionalPenaltyParameter(1.0)` and then I run a second simulation, but I pass the same penalty parameter with the `XHat` dictionary complete again.

I'll leave it up to you whether you would consider this a bug or not, but this is probably something the user should deal with. A warning in the error message cited at the start would probably not be amiss, so I will add it to my pull request.

**Comment by jmaack24** [comment]
I would consider this a bug as it results in unusual behavior that can be quite confusing to the user (as we have seen).  I'll have to think about the best way to fix it.  Some sort of reset function on the interface does seem like a good way to go.
